
global:
  scrape_interval:     5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'promswarmconnect'
    relabel_configs:
    - source_labels: [__meta_triton_machine_id]
      target_label: __address__
    - source_labels: [__meta_triton_server_id]
      target_label: __metrics_path__
    - source_labels: [__meta_triton_machine_alias]
      target_label: job
    triton_sd_configs:
    - account: 'dummyaccount'
      dns_suffix: 'dummy' # required
      endpoint: 'promswarmconnect'
      port: 443
      refresh_interval: 5s
      version: 1
      tls_config:
        insecure_skip_verify: true
