
global:
  scrape_interval:     5s
  evaluation_interval: 15s

# we have promswarmconnect scraper + static file-based scrapers for endpoints
# that are static at the moment.

# due to how Prometheus works, we have to configure distinct scrape jobs for each
# different scrape_interval :(

scrape_configs:
  - job_name: 'promswarmconnect'
    relabel_configs:
    - source_labels: [__meta_triton_machine_image]
      target_label: job
    - source_labels: [__meta_triton_machine_id]
      target_label: instance
    - source_labels: [__meta_triton_machine_alias]
      target_label: __address__
    - source_labels: [__meta_triton_machine_brand]
      target_label: __scheme__
    - source_labels: [__meta_triton_server_id]
      target_label: __metrics_path__
    tls_config:
      # can't specify this per-target, so since some of them can require insecure, sadly
      # we must specify this for all. shouldn't be too much of an issue, since services
      # are in LAN though
      insecure_skip_verify: true
    triton_sd_configs:
    - account: 'dummyaccount'
      dns_suffix: 'dummy' # required
      endpoint: 'promswarmconnect'
      port: 443
      refresh_interval: 5s
      version: 1
      tls_config:
        insecure_skip_verify: true
  - job_name: 'file_targets_5m'
    scrape_interval: 5m
    scrape_timeout: 20s
    scheme: https
    bearer_token_file: /etc/prometheus/scraper-bearer-token.secret
    relabel_configs:
      - target_label: instance 
        replacement: na
    file_sd_configs:
    - refresh_interval: 10s
      files:
      - "/etc/prometheus/static-targets/targets_5m.json"
  - job_name: 'file_targets_1h'
    scrape_interval: 1h
    scrape_timeout: 20s
    scheme: https
    bearer_token_file: /etc/prometheus/scraper-bearer-token.secret
    relabel_configs:
      - target_label: instance 
        replacement: na
    file_sd_configs:
    - refresh_interval: 10s
      files:
      - "/etc/prometheus/static-targets/targets_1h.json"
